import { youtubeTranscriptionService } from '../youtube-transcription.service';
import { YoutubeTranscript } from 'youtube-transcript';
import { logger } from '../logger';

// Mock dependencies
jest.mock('youtube-transcript');
jest.mock('../logger', () => ({
  logger: {
    info: jest.fn(),
    warn: jest.fn(),
    error: jest.fn(),
  },
}));

describe('YoutubeTranscriptionService', () => {
  const mockTranscript = [
    { text: 'Hola mundo', duration: 1000, offset: 0 },
    { text: 'Esto es una prueba', duration: 2000, offset: 1000 },
  ];

  beforeEach(() => {
    jest.resetAllMocks();
  });

  it('should get Spanish transcription successfully', async () => {
    (YoutubeTranscript.fetchTranscript as jest.Mock).mockResolvedValue(mockTranscript);

    const result = await youtubeTranscriptionService.getTranscription(
      'https://www.youtube.com/watch?v=123456',
    );

    expect(YoutubeTranscript.fetchTranscript).toHaveBeenCalledWith('123456', { lang: 'es' });
    expect(result.videoId).toBe('123456');
    expect(result.transcript).toBe('Hola mundo Esto es una prueba');
    expect(result.language).toBe('es');
  });

  it('should fallback to autogenerated transcription if Spanish fails', async () => {
    // First call fails
    (YoutubeTranscript.fetchTranscript as jest.Mock)
      .mockRejectedValueOnce(new Error('No captions'))
      .mockResolvedValueOnce(mockTranscript);

    const result = await youtubeTranscriptionService.getTranscription(
      'https://www.youtube.com/watch?v=123456',
    );

    // Expected: First call with es, Second call without options
    expect(YoutubeTranscript.fetchTranscript).toHaveBeenNthCalledWith(1, '123456', { lang: 'es' });
    expect(YoutubeTranscript.fetchTranscript).toHaveBeenNthCalledWith(2, '123456');
    expect(logger.warn).toHaveBeenCalled();
    expect(result.transcript).toBe('Hola mundo Esto es una prueba');
  });

  it('should throw error if both attempts fail', async () => {
    (YoutubeTranscript.fetchTranscript as jest.Mock).mockRejectedValue(
      new Error('No captions available'),
    );

    await expect(
      youtubeTranscriptionService.getTranscription('https://www.youtube.com/watch?v=123456'),
    ).rejects.toThrow('No se pudo obtener la transcripción');

    expect(YoutubeTranscript.fetchTranscript).toHaveBeenCalledTimes(2);
  });
});
