# Auto Assign Configuration

# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: author

# A list of reviewers to be added to pull requests
reviewers:
  - Alejandro

# A list of keywords to be skipped
skipKeywords:
  - wip
  - draft
