# GitHub Branch Protection Rules - God Level Configuration

# Main Branch Protection
main:
  required_status_checks:
    strict: true
    contexts:
      - ci/ci-cd
      - security/advanced-security
      - ai-ml/ai-code-review
      - performance/performance
      - monitoring/repository-analytics
      - dev-tools/integration-testing
      - security/dependency-security
      - security/secret-management
      - compliance/compliance
      - performance/performance-monitoring
  
  enforce_admins: true
  
  required_pull_request_reviews:
    required_approving_review_count: 2
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    require_last_push_approval: true
    dismiss_on_revert_request: true
    
  restrictions:
    users: []
    teams:
      - core-team
      - security-team
      - devops-team
      
  allow_force_pushes: false
  allow_deletions: false
  required_linear_history: true
  allow_fork_syncing: false

# Develop Branch Protection
develop:
  required_status_checks:
    strict: true
    contexts:
      - ci/ci-cd
      - security/advanced-security
      - ai-ml/ai-code-review
      - performance/performance
      - dev-tools/integration-testing
      
  enforce_admins: true
  
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    
  restrictions:
    users: []
    teams:
      - core-team
      - dev-team
      
  allow_force_pushes: false
  allow_deletions: false
  required_linear_history: true

# Staging Branch Protection
staging:
  required_status_checks:
    strict: true
    contexts:
      - ci/ci-cd
      - security/advanced-security
      - performance/performance
      - dev-tools/integration-testing
      
  enforce_admins: true
  
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    
  restrictions:
    users: []
    teams:
      - core-team
      - ops-team
      
  allow_force_pushes: false
  allow_deletions: false
  required_linear_history: true

# Feature Branch Rules
feature/*:
  required_status_checks:
    strict: false
    contexts:
      - ci/ci-cd
      - security/dependency-security
      
  enforce_admins: false
  
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: false
    
  restrictions:
    users: []
    teams:
      - dev-team
      
  allow_force_pushes: true
  allow_deletions: true
  required_linear_history: false

# Hotfix Branch Rules
hotfix/*:
  required_status_checks:
    strict: true
    contexts:
      - ci/ci-cd
      - security/advanced-security
      - performance/performance
      - dev-tools/integration-testing
      
  enforce_admins: true
  
  required_pull_request_reviews:
    required_approving_review_count: 2
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    
  restrictions:
    users: []
    teams:
      - core-team
      - security-team
      - ops-team
      
  allow_force_pushes: false
  allow_deletions: false
  required_linear_history: true

# Release Branch Rules
release/*:
  required_status_checks:
    strict: true
    contexts:
      - ci/ci-cd
      - security/advanced-security
      - security/dependency-security
      - ai-ml/ai-code-review
      - performance/performance
      - monitoring/repository-analytics
      - dev-tools/integration-testing
      - compliance/compliance
      
  enforce_admins: true
  
  required_pull_request_reviews:
    required_approving_review_count: 3
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    require_last_push_approval: true
    
  restrictions:
    users: []
    teams:
      - core-team
      - security-team
      - devops-team
      - release-team
      
  allow_force_pushes: false
  allow_deletions: false
  required_linear_history: true
