# GitHub Teams and Permissions - God Level Configuration

# ===========================================
# 👥 Core Teams
# ===========================================

core-team:
  description: 'Core development team with full repository access'
  members:
    - nemisanalex
    - admin@aigestion.net
  permissions:
    - admin
    - maintain
    - write
    - read
  repositories:
    - aigestion: admin
  teams:
    - maintain

security-team:
  description: 'Security team responsible for security policies and incident response'
  members:
    - security-lead@aigestion.net
    - security-engineer@aigestion.net
  permissions:
    - admin
    - maintain
    - write
    - read
  repositories:
    - aigestion: maintain
  teams:
    - maintain

devops-team:
  description: 'DevOps team responsible for CI/CD and infrastructure'
  members:
    - devops-lead@aigestion.net
    - devops-engineer@aigestion.net
  permissions:
    - admin
    - maintain
    - write
    - read
  repositories:
    - aigestion: maintain
  teams:
    - maintain

# ===========================================
# 🛠️ Development Teams
# ===========================================

frontend-team:
  description: 'Frontend development team'
  members:
    - frontend-lead@aigestion.net
    - frontend-dev1@aigestion.net
    - frontend-dev2@aigestion.net
  permissions:
    - write
    - read
  repositories:
    - aigestion: write
  teams:
    - write

backend-team:
  description: 'Backend development team'
  members:
    - backend-lead@aigestion.net
    - backend-dev1@aigestion.net
    - backend-dev2@aigestion.net
  permissions:
    - write
    - read
  repositories:
    - aigestion: write
  teams:
    - write

ai-team:
  description: 'AI/ML development team'
  members:
    - ai-lead@aigestion.net
    - ai-engineer@aigestion.net
  permissions:
    - write
    - read
  repositories:
    - aigestion: write
  teams:
    - write

# ===========================================
# 🔒 Specialized Teams
# ===========================================

release-team:
  description: 'Release management team'
  members:
    - release-manager@aigestion.net
    - devops-lead@aigestion.net
    - security-lead@aigestion.net
  permissions:
    - maintain
    - write
    - read
  repositories:
    - aigestion: maintain
  teams:
    - maintain

qa-team:
  description: 'Quality assurance team'
  members:
    - qa-lead@aigestion.net
    - qa-engineer1@aigestion.net
    - qa-engineer2@aigestion.net
  permissions:
    - write
    - read
  repositories:
    - aigestion: write
  teams:
    - write

compliance-team:
  description: 'Compliance and audit team'
  members:
    - compliance-officer@aigestion.net
    - audit-lead@aigestion.net
  permissions:
    - read
  repositories:
    - aigestion: read
  teams:
    - read

# ===========================================
# 👀 Review Teams
# ===========================================

code-reviewers:
  description: 'Code review team with review permissions'
  members:
    - senior-dev1@aigestion.net
    - senior-dev2@aigestion.net
    - tech-lead@aigestion.net
  permissions:
    - read
  repositories:
    - aigestion: read
  teams:
    - read

security-reviewers:
  description: 'Security review team for security-related changes'
  members:
    - security-lead@aigestion.net
    - security-engineer@aigestion.net
    - security-auditor@aigestion.net
  permissions:
    - read
  repositories:
    - aigestion: read
  teams:
    - read

# ===========================================
# 🌐 External Teams
# ===========================================

contractors:
  description: 'External contractors and consultants'
  members:
    - contractor1@external.com
    - contractor2@external.com
  permissions:
    - read
  repositories:
    - aigestion: read
  teams:
    - read

partners:
  description: 'Partner organizations'
  members:
    - partner1@partner.com
    - partner2@partner.com
  permissions:
    - read
  repositories:
    - aigestion: read
  teams:
    - read

# ===========================================
# 🤖 Bot Teams
# ===========================================

github-bots:
  description: 'GitHub bots and automation'
  members:
    - github-actions[bot]
    - dependabot[bot]
    - snyk-bot
    - codecov[bot]
  permissions:
    - write
    - read
  repositories:
    - aigestion: write
  teams:
    - write

# ===========================================
# 📊 Permission Matrix
# ===========================================

permission_matrix:
  admin:
    teams:
      - core-team
    capabilities:
      - repository administration
      - team management
      - branch protection
      - webhook management
      - secret management

  maintain:
    teams:
      - core-team
      - security-team
      - devops-team
      - release-team
    capabilities:
      - code management
      - issue management
      - pull request management
      - project management
      - release management

  write:
    teams:
      - core-team
      - security-team
      - devops-team
      - frontend-team
      - backend-team
      - ai-team
      - qa-team
      - github-bots
    capabilities:
      - code contribution
      - issue creation
      - pull request creation
      - project contribution

  read:
    teams:
      - all teams
    capabilities:
      - repository viewing
      - issue viewing
      - pull request viewing
      - project viewing

# ===========================================
# 🔄 Branch Access Rules
# ===========================================

branch_access:
  main:
    push:
      - core-team
    merge:
      - core-team
      - security-team
      - devops-team
    review:
      - core-team
      - security-team
      - devops-team
      - code-reviewers

  develop:
    push:
      - core-team
      - frontend-team
      - backend-team
      - ai-team
    merge:
      - core-team
      - dev-team
    review:
      - core-team
      - dev-team
      - code-reviewers

  staging:
    push:
      - core-team
      - devops-team
    merge:
      - core-team
      - devops-team
      - ops-team
    review:
      - core-team
      - devops-team
      - security-team

  feature/*:
    push:
      - core-team
      - frontend-team
      - backend-team
      - ai-team
      - qa-team
    merge:
      - core-team
      - dev-team
    review:
      - core-team
      - dev-team
      - code-reviewers

  hotfix/*:
    push:
      - core-team
      - security-team
      - devops-team
    merge:
      - core-team
      - security-team
      - devops-team
      - release-team
    review:
      - core-team
      - security-team
      - devops-team
      - security-reviewers

  release/*:
    push:
      - core-team
      - release-team
    merge:
      - core-team
      - release-team
      - security-team
      - devops-team
    review:
      - core-team
      - release-team
      - security-team
      - devops-team
      - security-reviewers
      - code-reviewers
