# 🌌 [GOD MODE] Cloud Build Pipeline - Simplified
# Fast deployment for AIGestion Backend

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '--tag'
      - 'gcr.io/$PROJECT_ID/backend:$BUILD_ID'
      - '--tag'
      - 'gcr.io/$PROJECT_ID/backend:latest'
      - '--file'
      - 'Dockerfile'
      - '.'

  # Step 2: Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/backend'
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run with God Mode configuration
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-service'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'backend-aigestion'
      - '--image'
      - 'gcr.io/$PROJECT_ID/backend:$BUILD_ID'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      # God Mode: Resource Configuration
      - '--cpu'
      - '4'
      - '--memory'
      - '8Gi'
      - '--cpu-boost'
      - '--execution-environment'
      - 'gen2'
      # God Mode: Autoscaling
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '32'
      - '--concurrency'
      - '80'
      # Networking & Security
      - '--port'
      - '8080'
      - '--allow-unauthenticated'
      - '--ingress'
      - 'all'
      # Timeout
      - '--timeout'
      - '300'
      # Environment variables
      - '--set-env-vars'
      - 'NODE_ENV=production,GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=europe-west1,ENABLE_REDIS=false'
    waitFor: ['push-image']

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: 'ALLOW_LOOSE'

# Timeout for entire build
timeout: '1200s'

# Images to push (for caching)
images:
  - 'gcr.io/$PROJECT_ID/backend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/backend:latest'
