name: '🚀 Feature Request'
description: 'Suggest an idea for AIGestion.'
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for a new feature? Tell us about it!
  - type: textarea
    id: feature-description
    attributes:
      label: 'Is your feature request related to a problem?'
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution you'd like"
      description: 'A clear and concise description of what you want to happen.'
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
  - type: checkboxes
    id: check-list
    attributes:
      label: 'Checklist'
      options:
        - label: 'I have checked that this feature is not already implemented.'
          required: true
        - label: 'This is a feature that would benefit the majority of users.'
          required: false
