/**
 * Design System - Main Export
 * Exportación principal del Design System AIGestion
 */

// Tokens
export { default as colors, colorUtils, cssColors } from './tokens/colors'
export { default as typography, typographyUtils, cssTypography } from './tokens/typography'
export { default as spacing, spacingUtils, cssSpacing } from './tokens/spacing'

// Components
export { default as Button } from './components/Button/Button'
export type { ButtonProps, ButtonVariant, ButtonSize } from './components/Button/Button'
export { default as Card, CardHeader, CardBody, CardFooter } from './components/Card/Card'
export type { CardProps, CardHeaderProps, CardBodyProps, CardFooterProps, CardVariant, CardSize } from './components/Card/Card'

// Theme
export const theme = {
  colors: {
    primary: {
      50: '#f0f9ff',
      500: '#0ea5e9',
      600: '#0284c7',
      700: '#0369a1',
    },
    secondary: {
      500: '#a855f7',
      600: '#9333ea',
      700: '#7c3aed',
    },
    accent: {
      500: '#ec4899',
      600: '#db2777',
      700: '#be185d',
    },
    neutral: {
      50: '#fafafa',
      100: '#f5f5f5',
      200: '#e5e5e5',
      300: '#d4d4d4',
      400: '#a3a3a3',
      500: '#737373',
      600: '#525252',
      700: '#404040',
      800: '#262626',
      900: '#171717',
    },
    semantic: {
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
    },
    gradients: {
      primary: 'linear-gradient(135deg, #0ea5e9 0%, #a855f7 50%, #ec4899 100%)',
      secondary: 'linear-gradient(135deg, #7c3aed 0%, #db2777 100%)',
      accent: 'linear-gradient(135deg, #f59e0b 0%, #ef4444 100%)',
      success: 'linear-gradient(135deg, #22c55e 0%, #16a34a 100%)',
      dark: 'linear-gradient(135deg, #0f0f23 0%, #1a1a3e 50%, #16213e 100%)',
      cosmic: 'linear-gradient(135deg, #667eea 0%, #764ba2 25%, #f093fb 50%, #f5576c 75%, #4facfe 100%)',
    },
  },
  typography: {
    fontFamily: {
      primary: '"Inter", system-ui, -apple-system, sans-serif',
      secondary: '"Space Grotesk", "Inter", system-ui, sans-serif',
      mono: '"JetBrains Mono", "Fira Code", monospace',
      display: '"Clash Display", "Inter", system-ui, sans-serif',
      gaming: '"Orbitron", "Space Mono", monospace',
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '3.75rem',
    },
    fontWeight: {
      light: 300,
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
    },
    lineHeight: {
      tight: 1.25,
      normal: 1.5,
      relaxed: 1.625,
    },
  },
  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    '2xl': '3rem',
    '3xl': '4rem',
    '4xl': '6rem',
    '5xl': '8rem',
  },
  borderRadius: {
    none: '0',
    sm: '0.25rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.75rem',
    '2xl': '1rem',
    '3xl': '1.5rem',
    full: '9999px',
  },
  shadows: {
    sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
    md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
    lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
    xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
    '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.25)',
    inner: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.05)',
    glow: '0 0 20px rgb(59 130 246 / 0.5)',
    neon: '0 0 20px rgb(6 182 212 / 0.8)',
  },
  animation: {
    duration: {
      fast: '150ms',
      normal: '300ms',
      slow: '500ms',
    },
    easing: {
      ease: 'cubic-bezier(0.4, 0, 0.2, 1)',
      easeIn: 'cubic-bezier(0.4, 0, 1, 1)',
      easeOut: 'cubic-bezier(0, 0, 0.2, 1)',
      easeInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
    },
  },
}

// CSS Custom Properties
export const cssTheme = {
  ':root': {
    '--color-primary-50': theme.colors.primary[50],
    '--color-primary-500': theme.colors.primary[500],
    '--color-primary-600': theme.colors.primary[600],
    '--color-primary-700': theme.colors.primary[700],
    '--color-secondary-500': theme.colors.secondary[500],
    '--color-secondary-600': theme.colors.secondary[600],
    '--color-secondary-700': theme.colors.secondary[700],
    '--color-accent-500': theme.colors.accent[500],
    '--color-accent-600': theme.colors.accent[600],
    '--color-accent-700': theme.colors.accent[700],
    '--color-neutral-50': theme.colors.neutral[50],
    '--color-neutral-100': theme.colors.neutral[100],
    '--color-neutral-200': theme.colors.neutral[200],
    '--color-neutral-300': theme.colors.neutral[300],
    '--color-neutral-400': theme.colors.neutral[400],
    '--color-neutral-500': theme.colors.neutral[500],
    '--color-neutral-600': theme.colors.neutral[600],
    '--color-neutral-700': theme.colors.neutral[700],
    '--color-neutral-800': theme.colors.neutral[800],
    '--color-neutral-900': theme.colors.neutral[900],
    '--color-success-500': theme.colors.semantic.success,
    '--color-warning-500': theme.colors.semantic.warning,
    '--color-error-500': theme.colors.semantic.error,
    '--color-info-500': theme.colors.semantic.info,
    '--gradient-primary': theme.colors.gradients.primary,
    '--gradient-secondary': theme.colors.gradients.secondary,
    '--gradient-accent': theme.colors.gradients.accent,
    '--gradient-success': theme.colors.gradients.success,
    '--gradient-dark': theme.colors.gradients.dark,
    '--gradient-cosmic': theme.colors.gradients.cosmic,
    '--font-primary': theme.typography.fontFamily.primary,
    '--font-secondary': theme.typography.fontFamily.secondary,
    '--font-mono': theme.typography.fontFamily.mono,
    '--font-display': theme.typography.fontFamily.display,
    '--font-gaming': theme.typography.fontFamily.gaming,
    '--text-xs': theme.typography.fontSize.xs,
    '--text-sm': theme.typography.fontSize.sm,
    '--text-base': theme.typography.fontSize.base,
    '--text-lg': theme.typography.fontSize.lg,
    '--text-xl': theme.typography.fontSize.xl,
    '--text-2xl': theme.typography.fontSize['2xl'],
    '--text-3xl': theme.typography.fontSize['3xl'],
    '--text-4xl': theme.typography.fontSize['4xl'],
    '--text-5xl': theme.typography.fontSize['5xl'],
    '--text-6xl': theme.typography.fontSize['6xl'],
    '--font-weight-light': theme.typography.fontWeight.light,
    '--font-weight-normal': theme.typography.fontWeight.normal,
    '--font-weight-medium': theme.typography.fontWeight.medium,
    '--font-weight-semibold': theme.typography.fontWeight.semibold,
    '--font-weight-bold': theme.typography.fontWeight.bold,
    '--font-weight-extrabold': theme.typography.fontWeight.extrabold,
    '--leading-tight': theme.typography.lineHeight.tight,
    '--leading-normal': theme.typography.lineHeight.normal,
    '--leading-relaxed': theme.typography.lineHeight.relaxed,
    '--spacing-xs': theme.spacing.xs,
    '--spacing-sm': theme.spacing.sm,
    '--spacing-md': theme.spacing.md,
    '--spacing-lg': theme.spacing.lg,
    '--spacing-xl': theme.spacing.xl,
    '--spacing-2xl': theme.spacing['2xl'],
    '--spacing-3xl': theme.spacing['3xl'],
    '--spacing-4xl': theme.spacing['4xl'],
    '--spacing-5xl': theme.spacing['5xl'],
    '--radius-sm': theme.borderRadius.sm,
    '--radius-md': theme.borderRadius.md,
    '--radius-lg': theme.borderRadius.lg,
    '--radius-xl': theme.borderRadius.xl,
    '--radius-2xl': theme.borderRadius['2xl'],
    '--radius-3xl': theme.borderRadius['3xl'],
    '--radius-full': theme.borderRadius.full,
    '--shadow-sm': theme.shadows.sm,
    '--shadow-md': theme.shadows.md,
    '--shadow-lg': theme.shadows.lg,
    '--shadow-xl': theme.shadows.xl,
    '--shadow-2xl': theme.shadows['2xl'],
    '--shadow-inner': theme.shadows.inner,
    '--shadow-glow': theme.shadows.glow,
    '--shadow-neon': theme.shadows.neon,
    '--duration-fast': theme.animation.duration.fast,
    '--duration-normal': theme.animation.duration.normal,
    '--duration-slow': theme.animation.duration.slow,
    '--ease-ease': theme.animation.easing.ease,
    '--ease-easeIn': theme.animation.easing.easeIn,
    '--ease-easeOut': theme.animation.easing.easeOut,
    '--ease-easeInOut': theme.animation.easing.easeInOut,
  },
}

export default theme
