#!/bin/bash
# 📋 ESTRUCTURA DEL PROYECTO - REFERENCIA RÁPIDA
# Última actualización: 1 de febrero de 2026

echo "════════════════════════════════════════════════════════════════"
echo "  🏗️  ESTRUCTURA AIGESTION v2.0 - REORGANIZADA"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "📊 CAMBIOS PRINCIPALES:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Frontend Workspace Creado:"
echo "   De:   AIGestion/aigestion/aigestion/frontend/"
echo "   A:    AIGestion/frontend/"
echo "   Por:  Simplificar estructura monorepo"
echo ""

echo "✅ Carpetas Elimiadas:"
echo "   - aigestion/aigestion/   (duplicada)"
echo "   - frontend-tmp/          (redundante)"
echo ""

echo "✅ Estructura Reorganizada:"
echo "   - .config/               ← Configuraciones globales"
echo "   - docs/                  ← Documentación"
echo "   - media/                 ← Imágenes, sonidos"
echo "   - .deploy/               ← Despliegue"
echo "   - .cache/                ← Archivos temporales"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "  📁 ESTRUCTURA ACTUAL"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "AIGestion/"
echo "├── 🔧 .config/                    ← Configuraciones"
echo "│   ├── tsconfig.json"
echo "│   ├── turbo.json"
echo "│   ├── eslint.config.mjs"
echo "│   └── ..."
echo "│"
echo "├── 📚 docs/                       ← Documentación"
echo "│   ├── README.md"
echo "│   ├── public/"
echo "│   └── ..."
echo "│"
echo "├── 📁 media/                      ← Multimedia"
echo "│   ├── images/"
echo "│   └── sounds/"
echo "│"
echo "├── .deploy/                       ← Despliegue (no versiona)"
echo "├── .cache/                        ← Caché (no versiona)"
echo "│"
echo "├── 🎯 Workspaces Principales"
echo "│   ├── backend/"                  ← API Backend"
echo "│   ├── frontend/                  ← Frontend Applications"
echo "│   │   ├── package.json"
echo "│   │   └── website-epic/          (aigestion.net)"
echo "│   └── packages/                  ← Librerías compartidas"
echo "│"
echo "├── 🧠 Otros (IA, Móvil, etc.)"
echo "│   ├── aig-ia-engine/             ← AI Engine"
echo "│   ├── android/                   ← React Native"
echo "│   ├── ai-tools/"
echo "│   ├── ml-service/"
echo "│   └── ..."
echo "│"
echo "└── 📦 Configuración Raíz"
echo "    ├── package.json               ← Workspaces config"
echo "    ├── .env.supabase              ← Env (tracking)"
echo "    ├── .env.gcp-divine            ← Env (tracking)"
echo "    └── *.code-workspace           ← VS Code"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "  ⚡ COMANDOS PRINCIPALES"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "# Desarrollo"
echo "  npm install                 # Instalar todas dependencias"
echo "  npm run dev                 # Backend + Frontend"
echo ""
echo "# Frontend"
echo "  cd frontend && npm run dev  # Dev frontend"
echo "  cd frontend/website-epic && npm run dev"
echo ""
echo "# Backend"
echo "  cd backend && npm run dev   # Dev backend"
echo ""
echo "# Build"
echo "  npm run build               # Build todo"
echo "  npm run build --prefix frontend"
echo "  npm run build --prefix backend"
echo ""
echo "# Testing"
echo "  npm run test                # Tests todo"
echo "  npm run lint                # Lint + Fix"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "  📂 ESTRUCTURA FRONTEND (Detalle)"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "frontend/                         ← Workspace raíz"
echo "├── package.json                  ← Define workspaces"
echo "│   {\"workspaces\": [\"website-epic\"]}"
echo "│"
echo "└── website-epic/                 ← App principal (aigestion.net)"
echo "    ├── src/"
echo "    │   ├── components/"
echo "    │   ├── pages/"
echo "    │   ├── hooks/"
echo "    │   ├── services/"
echo "    │   └── ....."
echo "    ├── public/"
echo "    ├── vite.config.ts"
echo "    ├── tsconfig.json"
echo "    ├── package.json"
echo "    └── index.html"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "  ✅ VERIFICACIONES COMPLETADAS"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✓ Frontend movido correctamente"
echo "✓ Carpetas aigestion/aigestion eliminadas"
echo "✓ frontend-tmp removido"
echo "✓ package.json frontend creado"
echo "✓ 5,728 archivos transferidos sin pérdida"
echo "✓ website-epic accesible en frontend/website-epic/"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "  📚 DOCUMENTACIÓN"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📄 Archivos de referencia:"
echo "  1. ESTRUCTURA_PROYECTO.md       - Estructura completa del proyecto"
echo "  2. REORGANIZACION_RESUMEN.md    - Resumen de cambios"
echo "  3. REORGANIZACION_COMPLETADA.md - Detalles de reorganización"
echo "  4. QUICK_REFERENCE.sh           - Este archivo (referencia rápida)"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "  🚀 PRÓXIMOS PASOS"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "1. npm install"
echo "2. npm run build"
echo "3. npm run lint"
echo "4. npm run test"
echo ""
echo "Status: ✅ LISTO PARA USAR"
echo ""
