action_id: trunk-share-with-everyone
date: 2026-01-15 07:48:28
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-share-with-everyone'. See .trunk\out\OcOLC.yaml for details.
  error_path: C:\Users\Alejandro\AIGestion\.trunk\out\OcOLC.yaml
timestamp: 1768463308
full_timestamp:
  nanos: 398947000
  seconds: 1768463308
trunk_version: 1.22.15
